name: Test Launch4j Installation

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'


      - name: Install Launch4j
        run: choco install launch4j -y

      - name: Check if Launch4j is installed
        run: |
          if (Test-Path "C:\Program Files (x86)\Launch4j") {
            Write-Host "✅ Launch4j is installed at C:\Program Files (x86)\Launch4j"
          } else {
            Write-Host "❌ Launch4j installation not found!"
            exit 1
          }

      - name: Check Java Installation Path
        run: where java
        shell: pwsh

      - name: Convert JAR to EXE
        run: |
          & C:\Program` Files` `(x86`)\Launch4j\launch4jc.exe config/launch4j-config.xml